# monitoring/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["api:8000"]  # Имя сервиса API из docker-compose.yml

  - job_name: "postgres"
    static_configs:
      - targets: ["db:9187"]  # Экспортер для PostgreSQL

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:9419"]  # Экспортер для RabbitMQ