name: Run FastAPI Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.override.yml up -d

      - name: Wait for services to be healthy
        run: |
          sleep 10

      - name: Run tests inside API container
        run: |
          docker exec -it ci_api pytest /app/tests/test_all.py --disable-warnings --maxfail=5
