name: Run FastAPI Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Load environment variables from GitHub Secrets
        run: echo "${{ secrets.ENV_VARS }}" > .env
      
      - name: Set up Docker Compose
        run: docker compose -f docker-compose.override.yml up -d

      - name: Wait for services to be healthy (wait untill all services start to be healthy)
        run: |
          sleep 30

      - name: Run tests inside API container
        run: docker exec ci_api pytest /app/tests/test_all.py --disable-warnings --maxfail=5

      - name: Stop and Clean Up Docker Containers
        if: always()
        run: docker compose -f docker-compose.override.yml down